version: '3'

services:

  flaskapp:
    build: .
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:1.13
    ports:
      - 5000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./templates:/templates
    restart: always
    depends_on:
      - flaskapp