apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
      - name: flaskapi-container
        image: djaybob/flaskapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapi-svc
spec:
  selector:
    app: flaskapi
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer